### ISSUE TITLE
Prevent overflow of news description for each card.

### ISSUE THREAD

**Issue by aswanthkoleri** [aswanthkoleri/OpenNews#11]

**Comment by AK-007** [comment]
@aswanthkoleri The description on the back side of flip cards right?

**Comment by aswanthkoleri** [comment]
@AK-007  Work on issue please ! :smile:

**Comment by aswanthkoleri** [comment]
And yes the description on the backside ! :smile:

**Comment by aswanthkoleri** [comment]
Issue solved by @AK-007
