### ISSUE TITLE
Add custom scroll bar for the webpage.

### ISSUE THREAD

**Issue by aswanthkoleri** [aswanthkoleri/OpenNews#14]

**Comment by AK-007** [comment]
I would like to work on this.

**Comment by aswanthkoleri** [comment]
@AK-007  First Fix your PR ! :smile:

**Comment by hacker1x1x1** [comment]
sir, can you assign this issue to  me?

**Comment by aswanthkoleri** [comment]
@hacker1x1x1 Assigned to you !

**Comment by aswanthkoleri** [comment]
Learn from this [link](https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp) ! The scroll bar should be long and it should have the gradient color of the background of the webpage. 
Look this site for reference : [Link](https://www.hackinthenorth.com)

**Comment by hacker1x1x1** [comment]
live link https://hacker1x1x1.github.io/OpenNews/
