### ISSUE TITLE
Remove the Website name from the Title part on the front portion of the Flip card.

### ISSUE THREAD

**Issue by aswanthkoleri** [aswanthkoleri/OpenNews#16]

**Comment by AK-007** [comment]
I would like to work on this issue.

**Comment by AK-007** [comment]
@aswanthkoleri Did you mean removing 'TechRadar' from front side of all flip cards under 'TechRadar' section , and similarly for others too?

**Comment by aswanthkoleri** [comment]
Yes exactly !
