### ISSUE TITLE
Change the size of Logo in readme

### ISSUE THREAD

**Issue by aswanthkoleri** [aswanthkoleri/OpenNews#17]

**Comment by aadixiiita** [comment]
I would like to work on this issue

**Comment by aswanthkoleri** [comment]
@aadixiiita  the logo is already created but just reduce the size in the readme ! :smile:

**Comment by Jigar3** [comment]
I would like to work on this issue @aswanthkoleri

**Comment by ashraysinha6069** [comment]
i would like to work on this issue
