### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by aswanthkoleri** [aswanthkoleri/OpenNews#2]

**Comment by Ace-Bansal** [comment]
I would like to work on this issue.

**Comment by aadixiiita** [comment]
I would like to work on this issue

**Comment by aswanthkoleri** [comment]
@Ace-Bansal  ! You may start working on it. Its just to add a simple footer.Don't add anything extra.Just add "Made with :heart:  by FOSSIIITA". I guess you know how to do it

**Comment by aswanthkoleri** [comment]
@aadixiiita Comment on one issue at time ! Later if your PR is accepted for that issue you can comment on other issues.Or if you cant solve the issue. Then comment that you can't do it . :smile:

**Comment by aswanthkoleri** [comment]
Issue solved by @Ace-Bansal
