### ISSUE TITLE
Editing the cards.

### ISSUE THREAD

**Issue by falconis** [aswanthkoleri/OpenNews#30]
Request to edit the styling of the cards, like adding shadows, adding detailings etc.

**Comment by hacker1x1x1** [comment]
i would love to work on this

**Comment by falconis** [comment]
Actually I was requesting if I could do it :sweat_smile:

**Comment by hacker1x1x1** [comment]
let the owner decide... D

**Comment by aswanthkoleri** [comment]
Both of you are not allowed to do it ! :stuck_out_tongue:  I will put up the issue .If you have any issue just comment on the issue #13 .

**Comment by falconis** [comment]
:joy: Alright!
